version: "3.1"

services:
  nginx:
    image: nginx:1.17
    working_dir: /laravel/www
    ports:
      - 80:80
    volumes:
      - ./:/laravel/www:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
      - phpmyadmin

  php:
    image: php:7.2-fpm-stretch
    working_dir: /laravel/www
    volumes:
      - ./:/laravel/www:cached
      - ./docker/php/php-fpm.d/custom.conf:/usr/local/etc/php-fpm.d/custom.conf
    environment:
      DB_HOST: mariadb
    links:
      - mariadb

  mariadb:
    image: mariadb:10.4
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      #- ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: I2U0Z6TddCFEq3uW

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:fpm-alpine
    environment:
      PMA_HOST: mysql
      PMA_ABSOLUTE_URI: http://127.0.0.1/pMA/
